name: Build and Push Docker to ECR

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # 3. Login to Amazon ECR
    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    # 4. Build Docker image
    - name: Build Docker image
      run: |
        docker build -t patient-service:latest .

    # 5. Tag Docker image for ECR
    - name: Tag Docker image
      run: |
        docker tag patient-service:latest 922718141448.dkr.ecr.eu-north-1.amazonaws.com/patient-service:latest

    # 6. Push Docker image to ECR
    - name: Push Docker image
      run: |
        docker push 922718141448.dkr.ecr.eu-north-1.amazonaws.com/patient-service:latest
